android: Remove WebGL max texture size limit
Igalia/wolvic-angle pull request #1
Opened 2023-09-19 20:03 UTC by tiagovignatti

2023-09-20 08:09 UTC, jdapena approved these changes

2023-09-20 08:09 UTC, jdapena commented on src/libANGLE/renderer/gl/renderergl_utils.cpp
> +    ANGLE_FEATURE_CONDITION(features, limitWebglMaxTextureSizeTo4096, limitMaxTextureSize);
Ditto, this could be problematic, and maybe we should instead have more specific conditions to override the 4096 limit.

GL drivers actually report this and we should honour that. So question is... How do we react when we know we cannot go over the 4096 (or even smaller) limit? Should we implement tiling?

2023-09-21 12:13 UTC, svillar requested changes
I think removing that limit could be quite risky indeed.

2023-10-02 18:26 UTC, tiagovignatti commented
> I think removing that limit could be quite risky indeed.

indeed.

I've now changed it to use an increased limit. PTAL.

2023-10-03 08:18 UTC, svillar approved these changes
Let's go for it

2023-10-03 08:18 UTC, merged